PipHarsveld/Hallo-Strandeiland

public/css/style.css
public/js/script.js
views/layouts/index.hbs
views/partials/header.hbs

De header is klaar deze kan toegevoegd worden aan de main.

Feature header

---

public/css/style.css
views/partials/footer.hbs

Feature footer

---

public/css/style.css

Ik heb padding toegevoegd aan het menu, zodat er nu wel ruimte tussen de zijkant en het menu is.

💄 Updated padding header #39

---

public/css/style.css
router/routes.js
views/wish.hbs

Ik heb de pagina gebouwd met HTML en CSS en deze is ook responsive gemaakt.
Ik hoor graag wat je ervan vind en of het zo goed is :).

HTML en CSS wens pagina

---

public/css/overview.css
public/css/style.css

:lipstick: Fix cardwidth and margin bottom

---

public/css/new-wish.css
public/css/style.css
public/scripts/script.js
router/routes.js
views/form.hbs

Ik heb ervoor gezocht dat de validatie nu geheel werkt op het formulier en dat het menu ook volledig tabbaar is. Daarnaast heb ik wat kleine extra dingentjes gefixed zoals dat wanneer je iets fout invult dat onderdeel gefocust word en je er ook heen scrolld. 
Als laatste krijg je nu wanneer je de wens aanmaakt je meteen naar de pagina van je nieuwe wens gaat en dus meteen te zien krijgt wat je hebt aangemaakt.
Ik hoor het graag als ik nog dingen moet aanpassen :)

:sparkles: Fixed form validation

---

router/routes.js

De data van de wishcards op de overview page komt nu uit de database

:boom: Wishes are being retrieved from API

---

views/main.hbs

Header van h2 naar h1 en de button op de homepagina gaat nu naar wens aanmaken

:adhesive_bandage: Fix header level and link

---

public/css/detail-wish.css
public/css/new-wish.css
public/scripts/script.js
router/routes.js
views/form.hbs
views/wish.hbs

Ik heb de feedback van de opdrachtgever doorgevoerd. De punten van de feedback kun je vinden in #111.
Ik hoor graag als er iets niet goed is!

:white_check_mark: Updated code from feedback #111

---

public/css/detail-wish.css
public/css/partials.css
public/css/style.css
public/scripts/script.js
router/routes.js
views/partials/wishcard.hbs
views/wish.hbs

Je kunt nu op alle drie de buttons klikken om iemand toe te voegen aan de sidebar en je kan nu ook een reactie toevoegen. Ook heb ik ervoor gezorgd dat de thema's die bij de wens horen worden opgehaald en dat alles er wat netter uit ziet.
Ik hoor graag wat je ervan vindt!

:sparkles: Buttons for sharing, helping or becoming an ambassador now work + add a comment

---

public/css/overview.css

De filters zijn nu responsive en issue #122 is nu opgelost!

:boom: Make filters responsive

---

public/css/overview.css
public/css/style.css
views/main.hbs

Ik heb een aantal warnings die we kregen in de console opgelost. Ook is de introtekst iets aangepast

Console warnings

---

public/css/detail-wish.css
public/css/partials.css
public/css/style.css
views/partials/header.hbs

Ik heb ervoor gezorgd dat de kleuren nu een goed contrast hebben en dat alles nu toegankelijk is met tab.

:wheelchair: Accessibility and contrast

---

router/routes.js
views/form.hbs
views/layouts/index.hbs
views/partials/themes.hbs

ThemaId was veranderd naar themeId waardoor er geen thema's meer werden ingeladen en de website kapot ging.
Ook heb ik al voor een paar pagina's comments geplaatst.

:card_file_box: Fixed bug themaId to themeId

---

public/scripts/script.js
server.js
views/wish.hbs

Ik heb code comments toegevoegd aan mijn deel van de code.
Laat maar weten of het zo goed is 😃

:bulb: Added code comments

---

router/routes.js

Ik heb comments aan de routes.js toevoegt aan het deel van de code dat ik heb geschreven.
Ik hoor graag wat je ervan vind :)

:bulb: Added comments

---

router/routes.js

Door een verandering in de database kregen wij een error, dat is nu opgelost.

:bug: Fix database themaId to themeId

---

router/routes.js

Ik heb er samen met Maijla voor gezorgd dat je er nu ook wanneer je een wens hebt aangemaakt de thema's zichtbaar worden en dat er nu een redirect is.

:bug: Fixed theme when new wish added

---

public/css/new-wish.css
public/css/overview.css
router/routes.js
server.js
views/form.hbs
views/main.hbs
views/partials/wishcard.hbs

Ik heb code comments toegevoegd en hier en daar de structuur van mijn code verbeterd.

💡 Code comments

---

public/css/new-wish.css

Ik heb een bug gefixed waar het formulier niet meer gecentreerd stond.

:bug: Fixed bug form not centered
